version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/mern-chat-circleci
    steps:
      - checkout
      - run: npm install
      - run: cd client && npm install
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cd client && npm install
      - run: npm run pretest
      - run: npm run test
  run:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install concurrently
      - run: npm install nodemon
      - run: npm run dev
workflows:
  version: 2.1
  build_and_test_and_run:
    jobs:
      - build
      - test
      - run
