version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/mern-chat-circleci
    steps:
      - checkout
      - run: npm install
      - run: npm test
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
